= Splitter

A *Minimal Viable Product (MVP)*, Splitter, is a simple tool that calculates the fair distribution of expenses among a group of people, ensuring that everyone pays their fair share based on the contributions they made during shared activities like trips or events.

== USER GUIDE

=== Step 1:
Clone the application.

=== Step 2:
Before using the project, you need to generate your OAuth Client-Secret and Client-ID on the GitHub website.

To do this, fill out the given form as follows:

* Your desired name for the project as the *Application name*.
* Use *http://localhost:9000* as the *Homepage URL*, as our application runs on port 9000.
* Optionally, provide a description.
* Use *http://localhost:9000* as the *Callback URL*.

You should now receive the Client-ID and the Client-Secret. Copy these as you will need them in the next step.

=== Step 3:
Enter the Client-Secret and Client-ID into the environment variables of the application.

=== Step 4:
Enter the *POSTGRES_USER* and *POSTGRES_PASSWORD*, which can be found in the `docker-compose.yml` file, into the environment variables.

=== Step 5:
To start the Docker container, first execute `docker compose up` in your Git Bash.

=== Step 6:
To start the application, use the following command:
`CLIENT_SECRET=SECRET CLIENT_ID=ID POSTGRES_USER=user POSTGRES_PASSWORD=password ./gradlew bootRun`

Replace `SECRET`, `ID`, `user`, and `password` with the values you set in the environment variables. Ensure that `user` and `password` match the values in the `docker-compose` file.

The application should now be running.

== Guide to the Web Interface

* On the homepage, you can add groups by entering the desired group name into the input field and clicking the *Add Group* button. Each group will have a hyperlink that directs you to the corresponding group information page.

* At the top of the page, you can search for groups, either open or closed ones.

=== In the Group Information Page:

* You can add members by entering their names into the input field at the top of the page. These names will then be listed individually below the input field.

* Below the member table, you'll find fields to input expenses. Fill out these fields as indicated by the labels.

* When specifying participants, always separate names with a comma and a space:
**Example:** Max, Lisa, Tim, Jan

* After filling out the inputs and selecting the payer, you can click the *Add Expense* button, and your expense will be displayed below the input fields.

* Once all expenses have been added, click the *Calculate Transactions* button to compute the required transactions for balancing the expenses. If you want to add another expense, you can do so and click *Calculate Transactions* again to get an updated calculation.

* If you wish to close the group, click the *Close Group* button. This will lock the group, making it no longer editable.

* Below the *Close Group* button, there's a hyperlink to return to the homepage. The group you just closed will now appear under closed groups. You can access the group's information via its hyperlink, but no further changes can be made.

== Authors

* *Erik Gal (PTamoynesis)*
* *Jamie Gerlach (JamieGFL)*
* *Iraj Masoudian (ixYozora)*
