name: build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./splitter
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install latest jdk
        uses: actions/setup-java@v4
        with:
          java-version: 25
          cache: 'gradle'
          distribution: 'temurin'
      - name: make gradlew executable
        run: chmod +x gradlew
      - name: run tests
        run: ./gradlew check
